### PR TITLE
Induc fix fb

### LINKED ISSUE #643: Undefined example in Test with Feedback
I quite often fall on this error while submitting answers. I think it happens when your algorithm to compute the feedback fails to find a good example to show

```
Uncaught TypeError: Cannot read property 'url' of undefined
    at ChooseImg (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:188841)
    at mountIndeterminateComponent (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:22848)
    at beginWork (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:23049)
    at performUnitOfWork (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25021)
    at workLoop (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25130)
    at HTMLUnknownElement.callCallback (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:13747)
    at HTMLUnknownElement.d (raven.js:386)
    at Object.invokeGuardedCallbackDev (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:13786)
    at invokeGuardedCallback (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:13643)
    at performWork (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25248)
    at batchedUpdates (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25692)
    at performFiberBatchedUpdates (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14094)
    at stackBatchedUpdates (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14085)
    at batchedUpdates (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14099)
    at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14112)
    at dispatchEvent (modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14322)
    at HTMLDocument.d (raven.js:386)
```
and 
```
ChooseImg @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:188841
mountIndeterminateComponent @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:22848
beginWork @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:23049
performUnitOfWork @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25021
workLoop @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25130
callCallback @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:13747
d @ raven.js:386
invokeGuardedCallbackDev @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:13786
invokeGuardedCallback @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:13643
performWork @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25248
batchedUpdates @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:25692
performFiberBatchedUpdates @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14094
stackBatchedUpdates @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14085
batchedUpdates @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14099
batchedUpdatesWithControlledComponents @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14112
dispatchEvent @ modules.js?hash=24a1e321878c9de1e5b12da715d6105038ff87bc:14322
d @ raven.js:386
raven.js:51 The above error occurred in the <ChooseImg> component:
    in ChooseImg
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal
    in Unknown
    in div (created by styled.div)
    in styled.div
    in Unknown (created by ac-induction)
    in div (created by styled.div)
    in styled.div (created by ac-induction)
    in ac-induction (created by ReactiveHOC(ac-induction))
    in ReactiveHOC(ac-induction) (created by Run)
    in Run
    in div
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal
    in Unknown (created by withState(Component))
    in withState(Component) (created by PreviewPage)
    in PreviewPage (created by Route)
    in Route (created by withRouter(PreviewPage))
    in withRouter(PreviewPage) (created by Route)
    in Route (created by TeacherContainer)
    in Switch (created by TeacherContainer)
    in div (created by TeacherContainer)
    in TeacherContainer (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by LoadableComponent)
    in LoadableComponent (created by Route)
    in Route (created by FROGRouter)
    in FROGRouter (created by Route)
    in Route
    in Switch
    in div
    in Router (created by BrowserRouter)
    in BrowserRouter
    in _ErrorBoundary
    in Unknown
```

### PR DESCRIPTION
**Pull request by romainAA**
I added a default color to the border of ImgBis
I checked that the feedback image isn't the same than the current one
I checked that there is an image for the corresponding feedback, otherwise I send a 'no image available' picture instead (but if the config is done right, this should never happen)

Closes #643

### CODE REVIEW

File: ac/ac-induction/src/TestPart/ModalSubmit.jsx [hunk 1]
```diff
@@ -133,11 +141,18 @@ const ChooseImg = ({ show, propertiesIndex, examples }: Object) => {
...
-    )[0].url;
+    );
   return (
     <div style={{ height: '200px', width: '100%' }}>
       {str}
-      <ImgBis url={url} color={show !== 3 ? '#00CC00' : '#CC0000'} />
+      <ImgBis
+        url={
+          urls === 'undefined'
+            ? 'http://www.bernunlimited.com/c.4436185/sca-dev-vinson/img/no_image_available.jpeg'
```
Comment (lfaucon) [inline ac/ac-induction/src/TestPart/ModalSubmit.jsx]: I don't like that you use an image from a random website. We don't want your activity to break if the website is taken down or simply changes. I'd rather use just a simple text saying the image is missing, or I think you can add the image in `frog/public/` and have it accessible with simply the name of the image as src

File: ac/ac-induction/src/TestPart/ModalSubmit.jsx [hunk 2]
```diff
@@ -133,11 +141,18 @@ const ChooseImg = ({ show, propertiesIndex, examples }: Object) => {
...
             )
-    )[0].url;
+    );
   return (
     <div style={{ height: '200px', width: '100%' }}>
       {str}
-      <ImgBis url={url} color={show !== 3 ? '#00CC00' : '#CC0000'} />
+      <ImgBis
+        url={
+          urls === 'undefined'
```
Comment (lfaucon) [inline ac/ac-induction/src/TestPart/ModalSubmit.jsx]: I don't see how that works. I expect `urls === []` or `url.length === 0` or `url[0] === undefined` 

The string `'undefined'` is not the same thing

**Review by lfaucon — CHANGES_REQUESTED** [review]

**Review by lfaucon — APPROVED** [review]
