### PR TITLE
Fix broken merge function

### LINKED ISSUE #1304: Third example  of ac-plot exampleData is broken

### PR DESCRIPTION
**Pull request by lfaucon**
Closes #1304

### CODE REVIEW

File: ac/ac-plot/src/index.js [hunk 1]
```diff
@@ -33,32 +33,36 @@ const config = {
...
 
-const mergeFunction = ({ data: incoming }, dataFn, data) => {
-  if (Array.isArray(incoming)) {
-    incoming.forEach(item => mergeFunction({ data: item }, dataFn, data));
-    return;
-  }
-  if (isEmpty(incoming) || !isObject(incoming)) {
-    return;
-  }
-  if (incoming['1']) {
```
Comment (lfaucon) [inline ac/ac-plot/src/index.js]: This is weird, did you write this special case to accept incomingData with the format:
`{  '1': { x, y, trace } }` ?
That looks arbitrary and unnatural to me. 
Made it so that the accepted types are only  `{x, y, trace}` or  `Array<{x, y, trace}>`

File: ac/ac-plot/src/index.js [hunk 2]
```diff
@@ -33,32 +33,36 @@ const config = {
...
-    mergeFunction({ data: incoming['1'] }, dataFn, data);
-  }
-  if (incoming.y) {
-    if (!data[incoming.trace]) {
-      dataFn.objInsert({ y: [] }, incoming.trace);
```
Comment (lfaucon) [inline ac/ac-plot/src/index.js:49]: I believe this was a bug. 
Does the `data` object changes synchronously when a dataFn function is called? I think it does not. This would then create bugs if we insert several points as we reinitialize the dataset for each point.

**Review by houshuang — CHANGES_REQUESTED** [review]
Does not work with streaming data from WISE. Probably something about how you're handling wrapped objects (taking away the 1: stuff).

Please test with graph WISE Simulation Demo.

If you think there's a good reason, you could suggest a change to the format of the data streamed by thermoCUp (although note that it's also compatible with ac-spreadsheet, which is currently working), or even with how the streaming function packages stuff (although again - a lot of activities are relying on the current way of working).

**Comment by lfaucon** [comment]
The problem was that I was expecting input of type `{trace, x, y}` but WISE simulation only sends `{trace, y}` expecting that by default x takes values 1,2,3,4,5...
